TOP = ../..
include $(TOP)/configure/CONFIG

DIRS += symbol
DIRS += edl

ADL_DIR = adl
UI_DIR  = ui/autoconvert
EDL_DIR = edl/autoconvert
OPI_DIR = opi/autoconvert
BOB_DIR = bob/autoconvert

include $(TOP)/configure/RULES_DIRS

-include $(SUPPORT)/configure/RULES_OPI
