#!/bin/sh
# This file was automatically generated on Tue 25 May 2010 16:29:05 BST from
# source: /dls_sw/work/R3.14.11/support/ffmpegServer/etc/makeIocs/example.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
cd "$(dirname "$0")"
#    export HOME_DIR="$(cd "$(dirname "$0")"/../..; pwd)"
# cd "$HOME_DIR"
./example stexample.boot
