@rem This file was automatically generated on Thu 24 Jul 2014 16:29:00 BST from
@rem source: /home/up45/github/ffmpegServer/etc/makeIocs/example_win32.xml
@rem 
@rem *** Please do not edit this file: edit the source file instead. ***
@rem 
@echo off
pushd %~dp0

if not [%1]==[] (
    set EPICS_CA_SERVER_PORT=%1
    set /a EPICS_CA_REPEATER_PORT=%1+1
    if not [%1] GEQ 0 (
        echo First argument %1 should be an integer greater than 0
        popd
        exit /B 1
    )
)
example_win32.exe stexample_win32.boot
popd
exit /B %ERRORLEVEL%
