# This file was automatically generated on Thu 24 Jul 2014 16:29:00 BST from
# source: /home/up45/github/ffmpegServer/etc/makeIocs/example_win32.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
< envPaths
cd "$(TOP)"

epicsEnvSet "EPICS_TS_MIN_WEST", '0'


# Loading libraries
# -----------------

# Device initialisation
# ---------------------

cd "$(TOP)"

dbLoadDatabase "dbd/example_win32.dbd"
example_win32_registerRecordDeviceDriver(pdbbase)

# simDetectorConfig(portName, maxSizeX, maxSizeY, dataType, maxBuffers, maxMemory)
simDetectorConfig("C1.CAM", 1600, 1200, 1, 50, 0)

ffmpegServerConfigure(8081)
# ffmpegStreamConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxMemory)
ffmpegStreamConfigure("C1.MJPG", 2, 0, "C1.CAM", "0", -1)

# ffmpegFileConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr)
ffmpegFileConfigure("C1.FILE", 16, 0, "C1.CAM", 0)

# Final ioc initialisation
# ------------------------
cd "$(TOP)"
dbLoadRecords 'db/example_win32_expanded.db'
iocInit
